services:
  app:
    build: .
    user: app
    command: /app/example/manage.py test
    volumes:
      - .:/app:cached
    environment:
      SHELL: /bin/bash
      IPYTHONDIR: /app/.ipython
      HISTFILE: /app/.bash_history
      PYTHONPATH: /app  # make django_languageselect available without installation
    restart: "no"
